environment: canary
cluster: prototype

serviceAccount:
  create: true
  annotations: {}
  name: ""

commonLabels:
  app.kubernetes.io/part-of: mantrachain-devnet-v1-resolute

deployment:

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

  envFrom: []
  env: {}

  livenessProbe: {}
  readinessProbe: {}

configMap: {}

service:
  enabled: true
  type: ClusterIP
  port: []

ingress: []

externalSecret:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 2