apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: resolute-redis-secrets
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  data:
    - secretKey: redis-password
      remoteRef:
        key: resolute-redis-secrets
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secrets-manager
  target:
    name: resolute-redis-secrets
    creationPolicy: Owner
