apiVersion: v1
kind: ConfigMap
metadata:
  name: resolute-server-devnet-v1-config
config.yaml: |
  active: "dev"

  dev:
    database:
      host: "postgresql"
      port: 5432
      user: "resolute"
      password: "heartland-ocean-praetor-neat"
      name: "resolute"
    api:
      port: 1323
    coingecko:
      uri: "https://api.coingecko.com/api/v3/"