apiVersion: v1
kind: ConfigMap
metadata:
  name: resolute-server-dukong-config
data:
  config.yaml: |
    active: "dev"

    # don't remove this prod config as it is used for global config
    production:
      api:
        port: 1323
      coingecko:
        uri: "https://api.coingecko.com/api/v3/"
      redisUri: "resolute-redis-dukong-master:6379"

    dev:
      database:
        host: "postgresql"
        port: 5432
        user: "resolute"
        password: "heartland-ocean-praetor-neat"
        name: "resolute"

  networks.json: |
    [
      {
        "chainId": "mantra-dukong-1",
        "restURIs": ["https://api.dukong.mantrachain.io:443"]
      },
    ]
