name: Docker Buildx - Standard

on:
  push:
    branches:
      - mantra
      - devops/configuring-CICD-k8s-deployment
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - mantra

env:
  REGISTRY: ${{ vars.REGISTRY || 'ghcr.io' }}

# Set concurrency for this workflow to cancel in-progress jobs if retriggered.
# The github.ref is only available when triggered by a PR so fall back to github.run_id for other cases.
# The github.run_id is unique for each run, giving each such invocation it's own unique concurrency group.
# Basically, if you push to a PR branch, jobs that are still running for that PR will be cancelled.
# But jobs started because of a merge to main or a release tag push are not cancelled.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  docker:
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: frontend
            image_name: ${{ github.event.repository.name }}-frontend
            build_args: |
              NEXT_PUBLIC_APP_API_URI=/api
          - context: server
            image_name: ${{ github.event.repository.name }}-server
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image_name }}            
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,enable=true,priority=100,prefix=,suffix=,format=short
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - 
        name: Define Variables
        id: vars
        run: |
          echo "::set-output name=version::`echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,'`"
      - 
        name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ matrix.build_args }}
